--[[
	Copyright (c) Rockstar Games 2005. All rights reserved.

	If you are going to use this in ANY of your projects in ANY non-commercial
cases — PLEASE include the original copyright notice. This code is not
originally authored by contributors to this repository and retains the
following legal terms:

	https://www.rockstargames.com/legal
	https://www.rockstargames.com/privacy

	https://www.take2games.com/legal
	https://www.take2games.com/privacy
--]]

--[[
	Every module but the DOCS and this one is made by AI (CODEX GPT5.5)


	~ Heve fun!
--]]

local script = script.REFRENTS

return {
	['sco'] = require(script.sco.Value),
	['compiler'] = require(script.compiler.Value),
	['interpreter'] = require(script.interpreter.Value),
	['Main'] = require(script.Main.Value),
	['DOCS'] = require(script.DOCS.Value),
}